### PR TITLE
feat: edit partial numbers

### PR DESCRIPTION
**Pull request by kilya11**
Currently edit a float number is a pain, because the decimal separator being the last char will be removed while typing.

Take use of the `userTyping` prop from antd to handle that case.

### CODE REVIEW

**Review by donAlDente — APPROVED** [review]

**Comment by mic-web** [comment]
Ich bin vom 28.09.2022  bis 04.10.2022  nicht erreichbar. Ihre E-Mail wird nicht weitergeleitet. In dringenden Fällen wenden Sie sich bitte an Herrn Igor Podolskiy ***@***.***  ***@***.***, Tel. +49-89-99017503).

Mit freundlichen Grüßen
Michael Adlfinger

I am out of office from 28.09.2022  till 04.10.2022 . Your email will not be forwarded. For urgent matters please contact Mr. Igor Podolskiy ***@***.***, phone +49-89-99017503).
Best regards
Michael Adlfinger
Currently edit a float number is a pain, because the decimal separator being the last char will be removed while typing.

Take use of the `userTyping` prop from antd to handle that case.
You can view, comment on, or merge this pull request online at:

  https://github.com/mll-lab/react-components/pull/187

-- Commit Summary --

  * feat: edit partial numbers

-- File Changes --

    M src/Fields/InputNumberField.tsx (18)

-- Patch Links --

https://github.com/mll-lab/react-components/pull/187.patch
https://github.com/mll-lab/react-components/pull/187.diff

-- 
Reply to this email directly or view it on GitHub:
https://github.com/mll-lab/react-components/pull/187
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***&gt;


To: "mll-lab/react-components" ***@***.***>

Cc: "Subscribed" ***@***.***>

Reply-To: "mll-lab/react-components" ***@***.***>

**Comment by mic-web** [comment]
Ich bin vom 28.09.2022  bis 04.10.2022  nicht erreichbar. Ihre E-Mail wird nicht weitergeleitet. In dringenden Fällen wenden Sie sich bitte an Herrn Igor Podolskiy ***@***.***  ***@***.***, Tel. +49-89-99017503).

Mit freundlichen Grüßen
Michael Adlfinger

I am out of office from 28.09.2022  till 04.10.2022 . Your email will not be forwarded. For urgent matters please contact Mr. Igor Podolskiy ***@***.***, phone +49-89-99017503).
Best regards
Michael Adlfinger
@donAlDente approved this pull request.





-- 
Reply to this email directly or view it on GitHub:
https://github.com/mll-lab/react-components/pull/187#pullrequestreview-1129580064
You are receiving this because you commented.

Message ID: ***@***.***>

To: "mll-lab/react-components" ***@***.***>

Cc: "mic-web" ***@***.***>

    "Comment" ***@***.***>

Reply-To: "mll-lab/react-components" ***@***.***>

**Comment by mic-web** [comment]
Ich bin vom 28.09.2022  bis 04.10.2022  nicht erreichbar. Ihre E-Mail wird nicht weitergeleitet. In dringenden Fällen wenden Sie sich bitte an Herrn Igor Podolskiy ***@***.***  ***@***.***, Tel. +49-89-99017503).

Mit freundlichen Grüßen
Michael Adlfinger

I am out of office from 28.09.2022  till 04.10.2022 . Your email will not be forwarded. For urgent matters please contact Mr. Igor Podolskiy ***@***.***, phone +49-89-99017503).
Best regards
Michael Adlfinger
:tada: This PR is included in version 11.7.0 :tada:

The release is available on:
- [npm package ***@***.*** ***@***.***/react-components/v/11.7.0)
- [GitHub release](https://github.com/mll-lab/react-components/releases/tag/v11.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

-- 
Reply to this email directly or view it on GitHub:
https://github.com/mll-lab/react-components/pull/187#issuecomment-1266655382
You are receiving this because you commented.

Message ID: ***@***.***>

To: "mll-lab/react-components" ***@***.***>

Cc: "mic-web" ***@***.***>

    "Comment" ***@***.***>

Reply-To: "mll-lab/react-components" ***@***.***>

**Comment by mic-web** [comment]
Ich bin vom 28.09.2022  bis 04.10.2022  nicht erreichbar. Ihre E-Mail wird nicht weitergeleitet. In dringenden Fällen wenden Sie sich bitte an Herrn Igor Podolskiy ***@***.***  ***@***.***, Tel. +49-89-99017503).

Mit freundlichen Grüßen
Michael Adlfinger

I am out of office from 28.09.2022  till 04.10.2022 . Your email will not be forwarded. For urgent matters please contact Mr. Igor Podolskiy ***@***.***, phone +49-89-99017503).
Best regards
Michael Adlfinger
Merged #187 into master.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/mll-lab/react-components/pull/187#event-7514446758
You are receiving this because you commented.

Message ID: ***@***.***>

To: "mll-lab/react-components" ***@***.***>

Cc: "mic-web" ***@***.***>

    "Comment" ***@***.***>

Reply-To: "mll-lab/react-components" ***@***.***>

**Pull request merged**
