### PR TITLE
feat: add space between modal buttons

### PR DESCRIPTION
**Pull request by mic-web**
Right now, modal buttons are glued together:

https://mll-lab.github.io/react-components/?path=/story/modal--open-by-button

This PR fixes the spacing between them by applying the styles like antd manually. Does not work out of the box because the specific antd classes with our prefix are not generated corectly.

### CODE REVIEW

**Review by spawnia — APPROVED** [review]

**Comment by spawnia** [comment]
@mic-web ready to go when conflicts are resolved.

**Comment by spawnia** [comment]
That was a very ugly commit message: https://github.com/mll-lab/react-components/commit/11c06cc9ea442200f9a152af2b893accfeb43e39. Better clear it next time.

**Comment by mic-web** [comment]
> That was a very ugly commit message: [11c06cc](https://github.com/mll-lab/react-components/commit/11c06cc9ea442200f9a152af2b893accfeb43e39). Better clear it next time.

You're right, I will.

**Comment by mic-web** [comment]
Ich bin vom 28.09.2022  bis 04.10.2022  nicht erreichbar. Ihre E-Mail wird nicht weitergeleitet. In dringenden Fällen wenden Sie sich bitte an Herrn Igor Podolskiy ***@***.***  ***@***.***, Tel. +49-89-99017503).

Mit freundlichen Grüßen
Michael Adlfinger

I am out of office from 28.09.2022  till 04.10.2022 . Your email will not be forwarded. For urgent matters please contact Mr. Igor Podolskiy ***@***.***, phone +49-89-99017503).
Best regards
Michael Adlfinger
@spawnia approved this pull request.





-- 
Reply to this email directly or view it on GitHub:
https://github.com/mll-lab/react-components/pull/186#pullrequestreview-1129674454
You are receiving this because you authored the thread.

Message ID: ***@***.***>

To: "mll-lab/react-components" ***@***.***>

Cc: "mic-web" ***@***.***>

    "Author" ***@***.***>

Reply-To: "mll-lab/react-components" ***@***.***>

**Pull request merged**
